var Figures = [	{
					name:"O",
					"1":{
						block1:{x:0,y:0},
						block2:{x:0,y:1},
						block3:{x:1,y:0},
						block4:{x:1,y:1}	
					}
				},
				{
					name:"I",
					"1":{
						block1:{x:0,y:0},
						block2:{x:0,y:1},
						block3:{x:0,y:2},	
						block4:{x:0,y:-1}
					},
					"2":{
						block1:{x:0,y:0},
						block2:{x:1,y:0},
						block3:{x:2,y:0},
						block4:{x:-1,y:0}	
					}
				},
				{
					name:"T",
					"1":{
						block1:{x:0,y:0},
						block2:{x:0,y:1},
						block3:{x:0,y:-1},	
						block4:{x:1,y:0}
					},
					"2":{
						block1:{x:0,y:0},
						block2:{x:0,y:1},
						block3:{x:1,y:0},
						block4:{x:-1,y:0}	
					},
					"3":{
						block1:{x:0,y:0},
						block2:{x:0,y:1},
						block3:{x:0,y:-1},
						block4:{x:-1,y:0}	
					},
					"4":{
						block1:{x:0,y:0},
						block2:{x:1,y:0},
						block3:{x:-1,y:0},
						block4:{x:0,y:-1}	
					}
				},
				{
					name:"J",
					"1":{
						block1:{x:0,y:0},
						block2:{x:0,y:1},
						block3:{x:-1,y:1},
						block4:{x:0,y:-1}	
					},
					"2":{
						block1:{x:0,y:0},
						block2:{x:-1,y:0},
						block3:{x:1,y:0},	
						block4:{x:-1,y:-1}
					},
					"3":{
						block1:{x:0,y:0},
						block2:{x:0,y:1},
						block3:{x:0,y:-1},
						block4:{x:1,y:-1}	
					},
					"4":{
						block1:{x:0,y:0},
						block2:{x:-1,y:0},
						block3:{x:1,y:0},
						block4:{x:1,y:1}	
					}
				},
				{
					name:"L",
					"1":{
						block1:{x:0,y:0},
						block2:{x:0,y:1},
						block3:{x:1,y:1},
						block4:{x:0,y:-1}	
					},
					"2":{
						block1:{x:0,y:0},
						block2:{x:-1,y:0},
						block3:{x:1,y:0},	
						block4:{x:-1,y:1}
					},
					"3":{
						block1:{x:0,y:0},
						block2:{x:0,y:1},
						block3:{x:0,y:-1},
						block4:{x:-1,y:-1}	
					},
					"4":{
						block1:{x:0,y:0},
						block2:{x:-1,y:0},
						block3:{x:1,y:0},
						block4:{x:1,y:-1}	
					}
				},
				{
					name:"S",
					"1":{
						block1:{x:0,y:0},
						block2:{x:1,y:-1},
						block3:{x:0,y:-1},	
						block4:{x:-1,y:0}
					},
					"2":{
						block1:{x:0,y:0},
						block2:{x:1,y:0},
						block3:{x:1,y:1},
						block4:{x:0,y:-1}	
					}
				},
				{
					name:"Z",
					"1":{
						block1:{x:0,y:0},
						block2:{x:-1,y:-1},
						block3:{x:0,y:-1},	
						block4:{x:1,y:0}
					},
					"2":{
						block1:{x:0,y:0},
						block2:{x:-1,y:1},
						block3:{x:-1,y:0},
						block4:{x:0,y:-1}	
					}
				}
];

